# site settings
title: appsparkler
subtitle: by aakash
email: appsparkler@gmail.com
description: web architect
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://aakashshah1.github.io # the base hostname & protocol for your site
author: aakash
street_address: Doddanekundi
city: Bangalore
state: KA
zip_code: 560037
country: India
formspreeEndpoint: https://formspree.io/f/mdojodbe

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/appsparkler
  Instagram: https://www.instagram.com/appsparklerin/
  LinkedIn: https://www.linkedin.com/in/appsparkler
  Twitter: https://twitter.com/isdeveloping
  Facebook: https://www.facebook.com/appsparkler

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
