# site settings
title: Muenchen Yoga
subtitle: Unite Body and Soul
email: gajendra.gulgulia@gmail.com
description: Hatha yoga - Beginners and Intermediate levels
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://ggulgulia.github.io # the base hostname & protocol for your site
author: Gajendra
street_address: Dachauer Str.
city: Munich
state: Bavaria
zip_code: 80992
country: Germany
formspreeEndpoint: https://formspree.io/f/xpznkbaj
branch: main
repo: ggulgulia/ggulgulia.github.io
google_analytics: G-3ZFPW8CPZT

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ggulgulia
  Instagram: https://www.instagram.com/appsparklerin/
  LinkedIn: https://www.linkedin.com/in/gajendra.gulgulia@gmail.com
  Twitter: https://twitter.com/isdeveloping
  Facebook: https://www.facebook.com/MuenchenYoga
  Meetup: https://www.meetup.com/munchen-yoga

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
